[general]
executable = "/mnt/SanDiskSSD/Nextcloud/Uni_Informatik/Master_Project/fluid_simulation_workspace/target/release/rusty_fluid_solver"
config_file = "/mnt/SanDiskSSD/Nextcloud/Uni_Informatik/Master_Project/fluid_simulation_workspace/rusty_fluid_solver/task6_measurement_scene_config.toml"
state_file = "/mnt/SanDiskSSD/Nextcloud/Uni_Informatik/Master_Project/fluid_simulation_workspace/state.ron"
measurement_destination_file_path = "/mnt/SanDiskSSD/Nextcloud/Uni_Informatik/Master_Project/rusty_measure/reproducibility_of_time_to_simulate_1s_system_time"
start_time = 5.0
finish_time = 6.0

[operation]
type = "Zip" # Zip, Cartesian

[parameters]
# time_increment = [0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009, 0.010, 0.011, 0.012, 0.013, 0.014, 0.015, 0.016, 0.017, 0.018, 0.019, 0.020,]
target_density_error = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]