[general]
executable = "/mnt/SanDiskSSD/Nextcloud/Uni_Informatik/Master_Project/fluid_simulation_workspace/target/release/rusty_fluid_solver"
config_file = "/mnt/SanDiskSSD/Nextcloud/Uni_Informatik/Master_Project/fluid_simulation_workspace/rusty_fluid_solver/task6_measurement_scene_config.toml"
state_file = ""
measurement_destination_file_path = "/mnt/SanDiskSSD/Nextcloud/Uni_Informatik/Master_Project/rusty_measure/SESPH_vs_IISPH_ii_20"
start_time = 15.0
finish_time = 16.0

[operation]
type = "Zip" # Zip, Cartesian

[parameters]
time_increment = [0.017, 0.012, 0.013, 0.009, 0.007, 0.005, 0.0035, 0.0025]
target_density_error = [0.8, 0.4, 0.2, 0.1, 0.05, 0.025, 0.0125, 0.00625]