# Scene configuration file

[parameters]
buffer_length_limit = 1000
integration_scheme = "EulerCromer" # Options: ExplicitEuler, ImplicitEuler, EulerCromer, Verlet,
rest_density = 900.0 # rest density of fluid
rest_density_grid_spacing = 0.8 # (not hot swappable)
smoothing_length = 0.8 # (not hot swappable)
disable_particles_below = -30
fluid_viscosity = 0.2
boundary_viscosity = 0.2
boundary_pressure_acceleration_weighting = 1.0 # gamma

# local pressure
stiffness = 15000000.0 # k
# global pressure
# solver_iterations = 5 # deprecated
target_density_error = 0.1 # in percent
relaxation_factor = 0.5 # omega
min_diagonal_element = 1e-25 # epsilon

# constant time step
time_increment = 0.01
# cfl time step
max_time_increment = 0.01
cfl_number = 0.4

[light]
position = [ 2.0, 30.0, 2.0 ] # (not hot swappable)

[scene]
type = "NoLidCube"

[scene.parameters.particles]
n_particles_x = 9
n_particles_y = 9
n_particles_z = 25
x_offset = 1.7
y_offset = 1.7
z_offset = 1.7
particle_spacing = 0.805

[scene.parameters.boundary_particles]
n_floor_particles_x = 14
n_floor_particles_y = 14
n_floor_particles_z = 2
wall_height = 50 # wall is at the edge but above floor
x_wall_thickness = 2
y_wall_thickness = 2
x_offset = 0.0
y_offset = 0.0
z_offset = 0.0
particle_spacing = 0.8

# [springs]
