# density_error_dependence_on_solver_iterations_and_time_increment
[general]
executable = "/mnt/SamsungSSD/Nextcloud/Uni_Informatik/Master_Project/fluid_simulation_workspace/target/release/rusty_fluid_solver"
config_file = "/mnt/SamsungSSD/Nextcloud/Uni_Informatik/Master_Project/fluid_simulation_workspace/rusty_fluid_solver/task6_measurement_scene_config.toml"
state_file = "/mnt/SamsungSSD/Nextcloud/Uni_Informatik/Master_Project/fluid_simulation_workspace/state.ron"
measurement_destination_file_path = "/mnt/SamsungSSD/Nextcloud/Uni_Informatik/Master_Project/rusty_measure/density_error_m1"
start_time = 5.0
finish_time = 15.0

[operation]
type = "Cartesian" # Zip, Cartesian

[parameters]
time_inc = [0.001, 0.003, 0.005, 0.007, 0.009, 0.01,]
solver_iterations = [5, 10, 15, 20, 25]